from ruuid.core import RUUID, VERSION, VARIANT_RFC4122, SIXTOFOUR_PREFIX
from ruuid.resolve import (
    DoHRegistry,
    HttpRegistry,
    Resolver,
    ResolveError,
    default_uuid_document_uri,
    fetch_document,
    fetch_url_body,
    identifier_label,
    resolve_referent_uri,
    resolve_ruuid,
    reverse_dns_name,
    substitute_template,
    synthesise_ruuid_document,
    to_ip,
    DEFAULT_REFERENT_URI_TEMPLATE,
    DEFAULT_UUID_DOCUMENT_URI_TEMPLATE,
    TXT_PREFIX,
)
from ruuid.generate import new_ruuid
from ruuid.schemes import IdentifierScheme

__all__ = [
    "RUUID",
    "VERSION",
    "VARIANT_RFC4122",
    "SIXTOFOUR_PREFIX",
    "new_ruuid",
    "Resolver",
    "HttpRegistry",
    "DoHRegistry",
    "ResolveError",
    "resolve_ruuid",
    "fetch_document",
    "fetch_url_body",
    "to_ip",
    "reverse_dns_name",
    "identifier_label",
    "substitute_template",
    "resolve_referent_uri",
    "synthesise_ruuid_document",
    "default_uuid_document_uri",
    "TXT_PREFIX",
    "DEFAULT_REFERENT_URI_TEMPLATE",
    "DEFAULT_UUID_DOCUMENT_URI_TEMPLATE",
    "IdentifierScheme",
]
